// <auto-generated />
using System;
using AndroidWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AndroidWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927165048_AddQueueStaffAndVaccinationStatus")]
    partial class AddQueueStaffAndVaccinationStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AndroidWebAPI.Models.Account", b =>
                {
                    b.Property<Guid>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferenceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.AccountOtp", b =>
                {
                    b.Property<Guid>("OTPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OTPCodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OTPID");

                    b.HasIndex("ParentID");

                    b.HasIndex("UserID");

                    b.ToTable("AccountOtps");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.Child", b =>
                {
                    b.Property<Guid>("ChildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Barangay")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("BirthHeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BirthWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ChildID");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.ChildParentRelationship", b =>
                {
                    b.Property<Guid>("RelationshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanReceiveNotifications")
                        .HasColumnType("bit");

                    b.Property<Guid>("ChildID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("bit");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RelationshipID");

                    b.HasIndex("ChildID");

                    b.HasIndex("ParentID");

                    b.ToTable("ChildParentRelationship", (string)null);
                });

            modelBuilder.Entity("AndroidWebAPI.Models.ClinicOperatingSchedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("QueueCutoffTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleID");

                    b.ToTable("ClinicOperatingSchedule");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.ClinicRoom", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<Guid?>("AssignedDoctorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentChildID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomID");

                    b.ToTable("ClinicRooms");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.ClinicScheduleException", b =>
                {
                    b.Property<int>("ExceptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExceptionID"));

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExceptionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("QueueCutoffTime")
                        .HasColumnType("time");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ExceptionID");

                    b.ToTable("ClinicScheduleExceptions");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChildID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoseNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("VaccineID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.Parent", b =>
                {
                    b.Property<Guid>("ParentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarangayNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TemporaryPasswordExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ParentID");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.Personnel", b =>
                {
                    b.Property<Guid>("PersonnelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PersonnelID");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.Queue", b =>
                {
                    b.Property<Guid>("QueueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AssignedRoomID")
                        .HasColumnType("int");

                    b.Property<Guid?>("AssignedStaffID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("QueueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaccinationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QueueID");

                    b.HasIndex("AssignedStaffID");

                    b.HasIndex("ParentID");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.QueueChild", b =>
                {
                    b.Property<Guid>("QueueChildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QueueID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QueueChildID");

                    b.HasIndex("ChildID");

                    b.HasIndex("QueueID");

                    b.ToTable("QueueChildren");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.QueueQRCode", b =>
                {
                    b.Property<Guid>("QRCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("QRDate")
                        .HasColumnType("date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("QRCodeID");

                    b.ToTable("QueueQRCodes");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.QueueQRSetting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingID"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SettingID");

                    b.ToTable("QueueQRSettings");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRCNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.VaccinationRecord", b =>
                {
                    b.Property<Guid>("VaccinationRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdministeredByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DoctorDiagnosedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DoctorDiagnosedByUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DoctorDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoseNumber")
                        .HasColumnType("int");

                    b.Property<int?>("InventoryID")
                        .HasColumnType("int");

                    b.Property<string>("NurseObservation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PersonnelID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecordCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TimelineID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VaccinationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaccineID")
                        .HasColumnType("int");

                    b.HasKey("VaccinationRecordID");

                    b.HasIndex("AdministeredByUserID");

                    b.HasIndex("ChildID");

                    b.HasIndex("DoctorDiagnosedByUserID");

                    b.HasIndex("InventoryID");

                    b.HasIndex("PersonnelID");

                    b.HasIndex("TimelineID");

                    b.HasIndex("VaccineID");

                    b.ToTable("VaccinationRecords");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.VaccinationScheduleRule", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoseNumber")
                        .HasColumnType("int");

                    b.Property<int>("IntervalFromPreviousDoseDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumAgeDays")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedAgeDays")
                        .HasColumnType("int");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaccineID")
                        .HasColumnType("int");

                    b.HasKey("RuleID");

                    b.HasIndex("VaccineID");

                    b.ToTable("VaccinationScheduleRules");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.VaccinationTimeline", b =>
                {
                    b.Property<Guid>("TimelineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoseNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimelineCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VaccinationRecordID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VaccineID")
                        .HasColumnType("int");

                    b.HasKey("TimelineID");

                    b.HasIndex("ChildID");

                    b.HasIndex("VaccinationRecordID");

                    b.HasIndex("VaccineID");

                    b.ToTable("VaccinationTimeline");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.Vaccine", b =>
                {
                    b.Property<int>("VaccineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineID"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdministrationRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgeCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoseInterval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfRequiredDoses")
                        .HasColumnType("int");

                    b.Property<string>("RecommendedAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TargetDisease")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaccineID");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.VaccineDose", b =>
                {
                    b.Property<int>("DoseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoseID"));

                    b.Property<int>("DoseNumber")
                        .HasColumnType("int");

                    b.Property<int>("MinIntervalDays")
                        .HasColumnType("int");

                    b.Property<int>("VaccineID")
                        .HasColumnType("int");

                    b.HasKey("DoseID");

                    b.HasIndex("VaccineID");

                    b.ToTable("VaccineDoses");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.VaccineInventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VaccineID")
                        .HasColumnType("int");

                    b.HasKey("InventoryID");

                    b.HasIndex("VaccineID");

                    b.ToTable("VaccineInventory");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.AccountOtp", b =>
                {
                    b.HasOne("AndroidWebAPI.Models.Parent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AndroidWebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.ChildParentRelationship", b =>
                {
                    b.HasOne("AndroidWebAPI.Models.Child", "Child")
                        .WithMany("ParentRelationships")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AndroidWebAPI.Models.Parent", "Parent")
                        .WithMany("ChildRelationships")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.Queue", b =>
                {
                    b.HasOne("AndroidWebAPI.Models.Personnel", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedStaffID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AndroidWebAPI.Models.Parent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedStaff");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.QueueChild", b =>
                {
                    b.HasOne("AndroidWebAPI.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AndroidWebAPI.Models.Queue", "Queue")
                        .WithMany("QueueChildren")
                        .HasForeignKey("QueueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.VaccinationRecord", b =>
                {
                    b.HasOne("AndroidWebAPI.Models.User", "AdministeredBy")
                        .WithMany()
                        .HasForeignKey("AdministeredByUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndroidWebAPI.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AndroidWebAPI.Models.User", "DoctorDiagnosedBy")
                        .WithMany()
                        .HasForeignKey("DoctorDiagnosedByUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AndroidWebAPI.Models.VaccineInventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryID");

                    b.HasOne("AndroidWebAPI.Models.Personnel", null)
                        .WithMany("VaccinationRecords")
                        .HasForeignKey("PersonnelID");

                    b.HasOne("AndroidWebAPI.Models.VaccinationTimeline", "Timeline")
                        .WithMany()
                        .HasForeignKey("TimelineID");

                    b.HasOne("AndroidWebAPI.Models.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("VaccineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministeredBy");

                    b.Navigation("Child");

                    b.Navigation("DoctorDiagnosedBy");

                    b.Navigation("Inventory");

                    b.Navigation("Timeline");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.VaccinationScheduleRule", b =>
                {
                    b.HasOne("AndroidWebAPI.Models.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("VaccineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.VaccinationTimeline", b =>
                {
                    b.HasOne("AndroidWebAPI.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AndroidWebAPI.Models.VaccinationRecord", "VaccinationRecord")
                        .WithMany()
                        .HasForeignKey("VaccinationRecordID");

                    b.HasOne("AndroidWebAPI.Models.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("VaccineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("VaccinationRecord");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.VaccineDose", b =>
                {
                    b.HasOne("AndroidWebAPI.Models.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("VaccineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.VaccineInventory", b =>
                {
                    b.HasOne("AndroidWebAPI.Models.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("VaccineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.Child", b =>
                {
                    b.Navigation("ParentRelationships");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.Parent", b =>
                {
                    b.Navigation("ChildRelationships");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.Personnel", b =>
                {
                    b.Navigation("VaccinationRecords");
                });

            modelBuilder.Entity("AndroidWebAPI.Models.Queue", b =>
                {
                    b.Navigation("QueueChildren");
                });
#pragma warning restore 612, 618
        }
    }
}
